# üå∏ 1 [WORKING WITH EXCEPTION CLASSES](https://learning.sap.com/learning-journeys/acquire-core-abap-skills/working-with-exception-classes_acd9568c-be4e-445a-a454-14c6f2cfcd2e)

> üå∫ Objectifs
>
> - [ ] Vous pourrez travailler avec des classes d'exception

## üå∏ EXCEPTION HANDLING

![](./assets/ExceptionClasses_001.png)

Plus t√¥t dans ce parcours d'apprentissage, nous avons √©tudi√© la gestion des erreurs √† l'aide des instructions `TRY`, `CATCH` et `ENDTRY`. Apr√®s l'instruction TRY vient l'instruction susceptible de provoquer une erreur. Si l'erreur se produit, le syst√®me passe √† l'instruction `CATCH` et traite son contenu. Quoi qu'il en soit, la m√©thode poursuit son traitement apr√®s l'instruction `ENDTRY`.

![](./assets/ExceptionClasses_002.png)

Dans un bloc `TRY‚Ä¶ENDTRY`, vous pouvez inclure plusieurs instructions `CATCH`. Cela vous permet de g√©rer diff√©remment les exceptions.

![](./assets/ExceptionClasses_003.png)

Vous pouvez lister plusieurs exceptions dans une seule instruction `CATCH`. Dans cet exemple, le m√™me bloc catch sera trait√© si le syst√®me d√©clenche `cx_sy_arithmetic_error` ou `cx_sy_zerodivide`.

![](./assets/ExceptionClasses_004.png)

Lorsqu'une classe est list√©e dans une instruction `CATCH`, le syst√®me traite le bloc correspondant si une exception li√©e √† cette classe ou √† l'une de ses sous-classes est d√©clench√©e. Dans cet exemple, `cx_sy_arithmetic_error` est une superclasse de `cx_sy_arithmetic_overflow` et de `cx_sy_zerodivide`. Par cons√©quent, le bloc est trait√© si une exception du type de l'une des sous-classes est lev√©e.

![](./assets/ExceptionClasses_005.png)

Toutes les classes d'exceptions font partie d'une hi√©rarchie d'h√©ritage dont la superclasse sup√©rieure est la classe `CX_ROOT`. Comme nous l'avons vu, si vous utilisez une superclasse dans une instruction CATCH, le syst√®me y acc√®dera si une exception du type de l'une de ses sous-classes est d√©clench√©e. Puisque toutes les classes d'exceptions sont des sous-classes de `CX_ROOT`, l'instruction CATCH `CX_ROOT` suffit √† intercepter n'importe quelle exception.

### SEQUENCE OF CATCH STATEMENTS

![](./assets/ExceptionClasses_006.png)

Lors de la r√©daction d'instructions `CATCH`, vous devez placer la ou les classes les plus sp√©cifiques en premier et les plus g√©n√©riques en dernier. Placer une superclasse au-dessus d'une de ses sous-classes entra√Ænera une erreur de syntaxe. En effet, le syst√®me ne pourra pas traiter le bloc `CATCH` sp√©cifique, car il est √©clips√© par le bloc plus g√©n√©rique.

### THE INTO ADDITION

Chaque exception est repr√©sent√©e par un objet. Vous pouvez placer cet objet dans une variable de r√©f√©rence et l'utiliser, par exemple pour r√©cup√©rer le texte d'erreur de la classe d'exception √† l'aide de la m√©thode `get_text()`, comme illustr√© dans l'exemple ci-dessous.

![](./assets/ExceptionClasses_007.png)

Vous pouvez utiliser une d√©claration en ligne dans l'instruction CATCH pour garantir que la variable de r√©f√©rence est d√©clar√©e avec le type correct.

L'action la plus courante avec l'objet exception est d'appeler sa m√©thode `get_text()`. Cependant, les objets exception peuvent poss√©der d'autres attributs et m√©thodes pour vous aider √† g√©rer l'erreur.

![](./assets/ExceptionClassesAttributes.png)

Les classes d'exception peuvent avoir des attributs d√©crivant plus pr√©cis√©ment le probl√®me. Ces attributs sont souvent utilis√©s pour remplir les espaces r√©serv√©s des messages. Vous d√©finissez l'attribut dans la section publique de la classe d'exception avec son nom et son type appropri√©s.

Pour remplir l'attribut lorsque l'exception est lev√©e, vous avez besoin d'un param√®tre d'importation correspondant du constructeur de la classe d'exception. Vous pouvez g√©n√©rer l'attribut √† l'aide d'un correctif rapide. Placez le curseur sur le nom de la m√©thode constructeur et appuyez sur [Ctrl] + [1]. Choisissez le correctif rapide `Re-generate constructor`.

### THE ATTRIBUTE "PREVIOUS"

Il arrive qu'au sein d'une cha√Æne d'appel, une m√©thode intercepte une exception. En r√©ponse, elle l√®ve une exception diff√©rente que son propre appelant doit intercepter. Cela peut se produire, par exemple, si un framework l√®ve une exception trop technique pour que l'application puisse la traiter elle-m√™me. Cependant, dans certains cas, la m√©thode qui effectue cette op√©ration (m√©thode 2 dans l'exemple) peut vouloir d√©clencher sa propre exception, tout en transmettant la premi√®re. Elle peut le faire gr√¢ce √† l'attribut previous de la classe d'exception.

![](./assets/ExceptionClasses_008.png)

Lorsque vous d√©clenchez une exception, vous pouvez transmettre une instance d'une classe d'exception au param√®tre d'importation pr√©c√©dent. Cela attache l'objet d'exception √† la nouvelle exception. Une m√©thode interceptant la seconde exception peut acc√©der au premier objet d'exception gr√¢ce aux attributs publics en lecture seule pr√©c√©dents.

Pr√©c√©dent est impl√©ment√© dans la superclasse `CX_ROOT` et est donc disponible dans toutes les classes d'exception.

![](./assets/PropagatingExceptions.png)

Une m√©thode n'a pas toujours besoin de g√©rer les exceptions d'une autre m√©thode qu'elle a appel√©e. Elle peut propager la m√©thode tout au long de la cha√Æne d'appel. Au lieu d'utiliser l'instruction `CATCH` pour g√©rer l'exception, la m√©thode inclut la clause `RAISING` dans sa d√©finition. Cela indique aux appelants de la m√©thode que l'exception peut leur √™tre transmise.

Si l'exception n'est pas intercept√©e tout au long de la cha√Æne d'appel, une erreur d'ex√©cution se produit.
